apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "deployment.fullname" $ }}
data:
  nginx.conf: |
    events {}
    stream {
      server {
        listen 80;
        proxy_pass {{ .Values.redirect_dst }};
      }
    }
